platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!

target 'VelocityRaptorCore_Example' do
  pod 'VelocityRaptorCore', :path => '../'

  target 'VelocityRaptorCore_Tests' do
    inherit! :search_paths

    
  end
end
